# Generated by Django 3.1.4 on 2020-12-01 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Title')),
                ('note_content', models.TextField(null=True, verbose_name='Content')),
                ('note_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Note created date/time')),
                ('note_last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Note last updated date/time')),
                ('note_is_archived', models.BooleanField(default=False, verbose_name='Archive')),
            ],
        ),
    ]
